name: Leju Ultimate Workflow

on:
  # 這個工作流程現在只接受一種觸發方式：
  # 由我們的 Google Sheet 發來的外部 API 命令
  repository_dispatch:
    types: [download-html]

jobs:
  # 我們現在只有一個工作，就叫做 build
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v3

    - name: 2. Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 3. Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    
    - name: 4. Run Downloader Script
      env:
        # 將所有需要的秘密變數和從外部傳入的參數設定為環境變數
        # 這是整個流程的關鍵
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        TARGET_URL: ${{ github.event.client_payload.url }}
        GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
      run: python downloader.py
